version: '3.8'
services:
  database:
    container_name: rest_api_test_postgres
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - database:/var/lib/postgresql/data
  cache:
    container_name: rest_api_test_redis
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
volumes:
  database:
    driver: local